language: node_js
node_js:
  - "8"
addons:
    code_climate:
        repo_token:
           secure: supersecuretokenencrypted
script: ./node_modules/.bin/nyc --reporter=lcov ./node_modules/mocha/bin/mocha --require @babel/register
before_script:
  - npm install codeclimate-test-reporter nyc -g
after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info
